version: '2'
services:
  postgresdb:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  ad-service:
    image: golang:1.11.1-alpine
    env_file:
      - .env
    volumes:
      - ./back-end:/go/src/github.com/ruybrito106/ads-manager-services/back-end
    links:
      - postgresdb
    working_dir: /go/src/github.com/ruybrito106/ads-manager-services/back-end
    command: go run cmd/ad_service/main.go
    ports:
      - "8084:8084"
  place-service:
    image: golang:1.11.1-alpine
    env_file:
      - .env
    volumes:
      - ./back-end:/go/src/github.com/ruybrito106/ads-manager-services/back-end
    links:
      - postgresdb
    working_dir: /go/src/github.com/ruybrito106/ads-manager-services/back-end
    command: go run cmd/place_service/main.go
    ports:
      - "8084:8084"
  auth-service:
    image: golang:1.11.1-alpine
    env_file:
      - .env
    volumes:
      - ./back-end:/go/src/github.com/ruybrito106/ads-manager-services/back-end
    links:
      - postgresdb
    working_dir: /go/src/github.com/ruybrito106/ads-manager-services/back-end
    command: go run cmd/auth_service/main.go
    ports:
      - "8083:8083"
  balance-service:
    image: golang:1.11.1-alpine
    env_file:
      - .env
    volumes:
      - ./back-end:/go/src/github.com/ruybrito106/ads-manager-services/back-end
    links:
      - postgresdb
    working_dir: /go/src/github.com/ruybrito106/ads-manager-services/back-end
    command: go run cmd/balance_service/main.go
    ports:
      - "8082:8082"
  campaign-service:
    image: golang:1.11.1-alpine
    env_file:
      - .env
    volumes:
      - ./back-end:/go/src/github.com/ruybrito106/ads-manager-services/back-end
    links:
      - postgresdb
    working_dir: /go/src/github.com/ruybrito106/ads-manager-services/back-end
    command: go run cmd/campaign_service/main.go
    ports:
      - "8081:8081"
  gateway-service:
    image: golang:1.11.1-alpine
    env_file:
      - .env
    volumes:
      - ./back-end:/go/src/github.com/ruybrito106/ads-manager-services/back-end
    links:
      - campaign-service
    working_dir: /go/src/github.com/ruybrito106/ads-manager-services/back-end
    command: go run cmd/gateway_service/main.go
    ports:
      - "8080:8080"
  front-end-service:
    build: ./front-end
    volumes:
      - './front-end:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development